# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/shikw/Documents/Program/Academic/VO/ORBVO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/shikw/Documents/Program/Academic/VO/ORBVO

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shikw/Documents/Program/Academic/VO/ORBVO/CMakeFiles /Users/shikw/Documents/Program/Academic/VO/ORBVO/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shikw/Documents/Program/Academic/VO/ORBVO/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Project

# Build rule for target.
Project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Project
.PHONY : Project

# fast build rule for target.
Project/fast:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/build
.PHONY : Project/fast

# target to build an object file
src/Frame.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/Frame.o
.PHONY : src/Frame.o

# target to preprocess a source file
src/Frame.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/Frame.i
.PHONY : src/Frame.i

# target to generate assembly for a file
src/Frame.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/Frame.s
.PHONY : src/Frame.s

# target to build an object file
src/Initializer.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/Initializer.o
.PHONY : src/Initializer.o

# target to preprocess a source file
src/Initializer.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/Initializer.i
.PHONY : src/Initializer.i

# target to generate assembly for a file
src/Initializer.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/Initializer.s
.PHONY : src/Initializer.s

# target to build an object file
src/KeyFrame.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/KeyFrame.o
.PHONY : src/KeyFrame.o

# target to preprocess a source file
src/KeyFrame.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/KeyFrame.i
.PHONY : src/KeyFrame.i

# target to generate assembly for a file
src/KeyFrame.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/KeyFrame.s
.PHONY : src/KeyFrame.s

# target to build an object file
src/Map.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/Map.o
.PHONY : src/Map.o

# target to preprocess a source file
src/Map.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/Map.i
.PHONY : src/Map.i

# target to generate assembly for a file
src/Map.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/Map.s
.PHONY : src/Map.s

# target to build an object file
src/MapPoint.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/MapPoint.o
.PHONY : src/MapPoint.o

# target to preprocess a source file
src/MapPoint.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/MapPoint.i
.PHONY : src/MapPoint.i

# target to generate assembly for a file
src/MapPoint.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/MapPoint.s
.PHONY : src/MapPoint.s

# target to build an object file
src/ORBVO.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/ORBVO.o
.PHONY : src/ORBVO.o

# target to preprocess a source file
src/ORBVO.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/ORBVO.i
.PHONY : src/ORBVO.i

# target to generate assembly for a file
src/ORBVO.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/ORBVO.s
.PHONY : src/ORBVO.s

# target to build an object file
src/ORBextractor.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/ORBextractor.o
.PHONY : src/ORBextractor.o

# target to preprocess a source file
src/ORBextractor.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/ORBextractor.i
.PHONY : src/ORBextractor.i

# target to generate assembly for a file
src/ORBextractor.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/ORBextractor.s
.PHONY : src/ORBextractor.s

# target to build an object file
src/ORBmatcher.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/ORBmatcher.o
.PHONY : src/ORBmatcher.o

# target to preprocess a source file
src/ORBmatcher.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/ORBmatcher.i
.PHONY : src/ORBmatcher.i

# target to generate assembly for a file
src/ORBmatcher.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/ORBmatcher.s
.PHONY : src/ORBmatcher.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Project"
	@echo "... src/Frame.o"
	@echo "... src/Frame.i"
	@echo "... src/Frame.s"
	@echo "... src/Initializer.o"
	@echo "... src/Initializer.i"
	@echo "... src/Initializer.s"
	@echo "... src/KeyFrame.o"
	@echo "... src/KeyFrame.i"
	@echo "... src/KeyFrame.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/MapPoint.o"
	@echo "... src/MapPoint.i"
	@echo "... src/MapPoint.s"
	@echo "... src/ORBVO.o"
	@echo "... src/ORBVO.i"
	@echo "... src/ORBVO.s"
	@echo "... src/ORBextractor.o"
	@echo "... src/ORBextractor.i"
	@echo "... src/ORBextractor.s"
	@echo "... src/ORBmatcher.o"
	@echo "... src/ORBmatcher.i"
	@echo "... src/ORBmatcher.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

